trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: 'Install Dependencies'

- script: npm test
  displayName: 'Run Tests'

- script: npm run build
  displayName: 'Build Application'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'dist'
    artifactName: 'myApp'
