# This is a basic workflow to help you get started with Actions




name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

        

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.





      - name: CodeClimate Code Coverage Test Reporter
  # You may pin to the exact commit or the version.
  # uses: xylabs/action-code-climate-test-reporter@79e542e6c82c5c48a50e885860eeed998467bbe5
        uses: xylabs/action-code-climate-test-reporter@v1.0.0
        with:
    # The cc-test-report subcommand (with flags/arguments) to execute
          subcommand: help


      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
    # Artifact name
          name: Output
    # Destination path
          path: C:\Users\unico\OneDrive\Documents\Software Development (2nd Year)\Semester 2\DOE522\Practical Exam
          


      - name: Inclusiveness Analyzer
        uses: microsoft/InclusivenessAnalyzer@v1.0.1
        with:
    # Fails the step if a non-inclusive term is found
          failOnNonInclusiveTerm: false
    # Only scan files added or modified in last commit when checkout step has "with: fetch-depth: 2" configured
          excludeUnchangedFiles: true
    # Comma separated list of file patterns to exclude from analysis
          excludeFiles: # optional
    # Comma separated list of non-inclusive terms to exclude from analysis
          excludeTerms: # optional
          




